import { Provider } from "@/components/ui/provider";
import type { Metadata } from "next";
import { AiFillLinkedin } from "react-icons/ai";
import { AiFillGithub } from "react-icons/ai";
import { AiOutlineMail } from "react-icons/ai";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import '@/styles/_main.scss'
import { Avatar, IconButton } from "@chakra-ui/react";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Provider>
        <body>
          <header id="header">
            <div className="wrapper">
              <p>Auston</p>
              <Avatar.Root size={'2xl'}>
                <Avatar.Fallback name="Usual SNS Icon" />
                <Avatar.Image src='/sensei.webp'/>
              </Avatar.Root>
              <p>Pawell</p>
            </div>
          </header>
            <main>
                {children}
            </main>
          <footer id="footer">
            <div className="wrapper">
                <img src="/logo.png" alt="" />
                <div className="socials-container">
                  <a href="https://www.linkedin.com/in/apawell" target="_blank">
                    <IconButton size={'lg'}>
                      <AiFillLinkedin />
                    </IconButton>
                  </a>
                  <a href="https://github.com/Nepgyah" target="_blank">
                    <IconButton size={'lg'}>
                      <AiFillGithub />
                    </IconButton>
                  </a>
                  <a href="mailto:auston.pawell@gmail.com" target="_blank">
                    <IconButton size={'lg'}>
                      <AiOutlineMail />
                    </IconButton>
                  </a>
                </div>
                <div className="divider"></div>
            </div>
          </footer>
        </body>
      </Provider>
    </html>
  );
}
