import { Provider } from "@/components/ui/provider";
import type { Metadata } from "next";
import { AiFillLinkedin } from "react-icons/ai";
import { AiFillGithub } from "react-icons/ai";
import { AiOutlineMail } from "react-icons/ai";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import '@/styles/_main.scss'
import { IconButton } from "@chakra-ui/react";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Provider>
        <body>
          <header id="header">
            <div className="wrapper">
              <p>Auston Pawell</p>
            </div>
          </header>
            <main>
                {children}
            </main>
          <footer id="footer">
            <div className="wrapper">
                <img src="/logo.png" alt="" />
                <div className="socials-container">
                  <IconButton>
                    <AiFillLinkedin />
                  </IconButton>
                  <IconButton>
                    <AiFillGithub />
                  </IconButton>
                  <IconButton>
                    <AiOutlineMail />
                  </IconButton>
                </div>
            </div>
          </footer>
        </body>
      </Provider>
    </html>
  );
}
